config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'dashboard/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
   root "dashboard#index"

   resources :people

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document_type.rb
class DocumentType < ApplicationRecord
	has_many :person
end

app/models/person.rb
class Person < ApplicationRecord
	belongs_to :document_type
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #belongs_to :document_type        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base 
	protect_from_forgery with: :exception
#	skip_before_action :verify_authenticity_token
#	protect_from_forgery with: :exception 
#	before_action :update_allowed_parameters , 	if:	:devise_controller? 

#	protected 
#	def update_allowed_parameters 
#		devise_parameter_sanitizer.permit( :sign_up ) { |u| u.permit( :email , :password, :name, :main_phone, :secondary_phone, :document_number, :document_emission_date, :document_expire_date )} 
#		devise_parameter_sanitizer.permit( :account_update ) { |u| u.permit( :email , :password , :current_password, :main_phone, :secondary_phone )} 
#	end 
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	
	#protect_from_forgery with: :exception
  	#skip_before_action :verify_authenticity_token  
    before_action :authenticate_user!

	def index
		@people = Person.all
	end


	def show
		@person = Person.find(params[:id])
	end


	def new
		@person = Person.new
	end

	
	def create
		person_params_aux = person_params
		person_params_aux[:document_types_id] = DocumentType.find(params[:document_types_id])
		
		@person= Person.create! person_params_aux 

	  if @person.persisted?
		  redirect_to people_path, notice: "Person Created"
	  else
		  render :new, status: :unprocessable_entity
	  end
	end


	def edit
		@person = Person.find(params[:id])
	end


	def update
		@person = Person.find(params[:id])
		@person.update person_params_update
		if @person.update person_params_update
			redirect_to people_path, notice: "Person Updated"
		else
			render :edit, status: :unprocessable_entity
		end
	end


	def destroy
		@person = Person.find(params[:id])
		@person.destroy
		redirect_to people_path,
		status: :see_other, notice: "Person Deleted"
	end

	private

		# strong params
		def person_params
			params.require(:person).permit(:name, :email, :document_emission_date, :document_expire_date, :main_phone, :secondary_phone, :document_types_id, :document_number)
		end
		def person_params_update
			params.require(:person).permit(:name, :email, :main_phone, :secondary_phone)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Siscobank</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= url_for(controller: "/dashboard", action: "index") %>">Home</a>
        </li>
        <% if !current_user %>

       
       
        <li class="nav-item">         
          <a class="nav-link" href="<%= url_for(controller: "devise/sessions", action: "new") %>">Login
          </a>
        </li>
        <%end%>

        <% if current_user %>
        <li class="nav-item">
           <a class="nav-link" href="<%= url_for(controller: "/people", action: "index") %>">Register Person
          </a>
        </li>

        <li class="nav-item">        
          
            <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class:"nav-link" %>
        
        </li>
        

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
        <%end%>
      </ul>
      
    </div>
  </div>
</nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Edit Person</h1>

<%= form_with model: @person do |f| %>
<% if @person.errors.any? %>
    <div style="color: red">
      <h3><%= pluralize(@person.errors.count, "error") %> :</h3>

      <ul>
        <% @person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email"  %>
  </div>

   <div> 
    <%= f.label :name %> <br /> 
    <%= f.text_field :name %> 
  </div> 

   <div> 
    <%= f.label :document_emission_date %> <br /> 
    <%= f.text_field :document_emission_date %> 
  </div> 

   <div> 
    <%= f.label :document_expire_date %> <br /> 
    <%= f.text_field :document_expire_date %> 
  </div>     

   <div> 
    <%= f.label :main_phone %> <br /> 
    <%= f.text_field :main_phone %> 
  </div>     

   <div> 
    <%= f.label :secondary_phone %> <br /> 
    <%= f.text_field :secondary_phone %> 
  </div>  
  


  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/people/index.html.erb
<h1>People List</h1>

<div class="table-responsive">
  <table class="table">
      <thead class="table-light">
        <tr>
	      	<td>id</td>
	      	<td>email</td>
	      	<td>name</td>
	      	<td>actions</td>
 		</tr>
	  </thead>
	  <tbody>
	     <% @people.each do |row| %>
	     <tr>
	        <td><%= row.id %></td>
	        <td><%= row.email %></td>
	        <td class="align-top"><%= row.name %></td>
	        <td><%= link_to 'Show', person_path(row.id) %></td>
        </tr>        
        <% end %>

	  </tbody>

  </table>
</div>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= form_with model: @person do |f| %>

<% if @person.errors.any? %>
    <div style="color: red">
      <h3><%= pluralize(@person.errors.count, "error") %> :</h3>

      <ul>
        <% @person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

   <div> 
    <%= f.label :name %> <br /> 
    <%= f.text_field :name %> 
  </div> 

   <div> 
    <%= f.label :document_emission_date %> <br /> 
    <%= f.text_field :document_emission_date %> 
  </div> 

   <div> 
    <%= f.label :document_expire_date %> <br /> 
    <%= f.text_field :document_expire_date %> 
  </div>     

   <div> 
    <%= f.label :main_phone %> <br /> 
    <%= f.text_field :main_phone %> 
  </div>     

   <div> 
    <%= f.label :secondary_phone %> <br /> 
    <%= f.text_field :secondary_phone %> 
  </div>     

   <div> 
    <%= f.label :document_types_id %> <br /> 
      <%= f.collection_select :document_types_id, DocumentType.order(:name),:id,:name, include_blank: true %>

  </div>  
   <div> 
    <%= f.label :document_number %> <br /> 
    <%= f.text_field :document_number %> 
  </div>   


  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/people/show.html.erb
<div>
	<p><h2><%= @person.name%></h2></p>
	<p>email: <%= @person.email %></p>	
	<p><%= @person.main_phone %></p>
  <p><%= @person.secondary_phone %></p>
  <p>document_number:<%= @person.document_number %></p>
  <p>document_emission_date: <%= @person.document_emission_date %></p>
	<p>document_expire_date:<%= @person.document_expire_date %></p>
	<%= link_to 'Edit', edit_person_path(@person) %>
	<%= button_to 'delete', person_path(@person), method: :delete, data: {  turbo_confirm: 'Are you sure?'} %>
</div>